from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Literal

class BrainContext(BaseModel):
    """Shared state object passed between brain regions."""
    original_query: str
    plan: Optional[List[str]] = Field(default=None, description="Steps generated by PFC")
    memories: Optional[List[str]] = Field(default=None, description="Context from Hippocampus")
    logical_facts: Optional[List[str]] = Field(default=None, description="Facts from Left Brain")
    creative_draft: Optional[str] = Field(default=None, description="Draft from Right Brain")
    final_output: Optional[str] = None
    
    # Metadata for tracking the process
    current_stage: str = "Input"
    logs: List[str] = Field(default_factory=list)

    def add_log(self, source: str, message: str):
        # Print immediately for real-time user feedback
        print(f"[{source}] {message}")
        self.logs.append(f"[{source}] {message}")
